### ISSUE TITLE
Static Files S3

### ISSUE THREAD

**Issue by John0x** [maciejtreder/angular-universal-pwa#102]
Hello, could you please elaborate a bit more on the subject of why you're not using S3 to store the static files?
It would be much cheaper or not? Especially with multiple bundles and async loading.

**Comment by mattmeye** [comment]
+1 @maciejtreder 200ms is noteable for seo

**Comment by maciejtreder** [comment]
@John0x @mattmeye

There are two major reasons:
 
1. I was running into a lot of issues with CORS on Chrome:
https://zyst.io/how-to-fix-aws-s3-chrome-and-safari-cors-on-images
https://stackoverflow.com/questions/20253472/cors-problems-with-amazon-s3-on-the-latest-chomium-and-google-canary

There is much more about that on the web.


2. I am focusing on automation of deployment process in this repository. I want make it running on developers end just 'out of the box'. Serving static files from s3 need a lot of manual setup.
