### ISSUE TITLE
Cannot read property 'config' of null

### ISSUE THREAD

**Issue by tibinthomas** [maciejtreder/angular-universal-pwa#104]
What to do ?

Angular CLI: 1.6.7
Node: 8.5.0
OS: win32 x64
Angular: 5.2.3
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker

@angular/app-shell: 0.1.0
@angular/cdk: 5.2.0
@angular/cli: 1.6.7
@angular/material: 5.2.0
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.7
@schematics/angular: 0.1.17
typescript-collections: 1.3.2
typescript: 2.7.1
webpack-dev-server: 2.11.1
webpack-merge: 4.1.1
webpack: 3.10.0

**Comment by maciejtreder** [comment]
@tibinthomas Could you provide more information about the situation in which this error occurred? Giving error log would be great.
