### ISSUE TITLE
No SEO?

### ISSUE THREAD

**Issue by martinambrus** [maciejtreder/angular-universal-pwa#106]
Hi, and let me start by saying thank you for this amazing project! I tried to fork and use it and even upgraded it to the latest Angular version. But then a major drawback struck me in the face. There is no SEO :(

I mean, the server-side generated pages do not have any of the text you see when you load the page with JavaScript. The means that search engines will also not see the text of any of the modules, not even a homepage, just a generic template that's the same for every page.

Also, I've got a question about external modules. What good are they if we still need to recompile the whole app when that module changes in a different directory somewhere on GitHub?

Thanks!

**Comment by maciejtreder** [comment]
Hello,

Thank you for your feedback. Demo, deployed on AWS lambda works correclty (server side rendering also).

Try:

`curl -i https://www.angular-universal-pwa.maciejtreder.com`

You should check your back-end console for more info about possible issue.


Regarding external modules. What I am going to implement is something what would give developer possibility to swap external module, without recompiling whole app.


Star repo, watch for changes and be patient :)

**Comment by martinambrus** [comment]
Oh wow, sorry, you're right of course!

I was under the impression that Chrome will show me the server-side source when I go via Show Source, just like Firefox does... but Chrome actually shows the *current* source code, which is indeed showing just the `<app></app>` tag without any content - and that's correct.

Thanks for clearing up my confusion and thanks for answering the external mods question as well :)

**Comment by vahidvdn** [comment]
Hi @maciejtreder . Thanks for this awesome project. I have a question about SSR in your demo app. Why does loading with `curl` work fine, but when using `View page source` it doesn't load content?
