### ISSUE TITLE
Translations question

### ISSUE THREAD

**Issue by martinambrus** [maciejtreder/angular-universal-pwa#122]
Hi!

Nice to see you're making progress and integrating the FireBug stuff - that's quite a nice touch there :)
I tried to implement translations via https://www.npmjs.com/package/@ngx-translate/core but that only worked for the local server and failed for the AOT compiled one. Would you have any experience in implementing this, please? I would really appreciate a nudge in the right direction. All the code does now is returning a textual "Error" line on the page and nothing else, so I'm kinda stuck on what could this be causing.

I'm basically using this to accomplish the translation: https://www.npmjs.com/package/@ngx-translate/core#aot

I've just spent so much time trying to debug and solve this that I'm willing to put up a donation for you if you'd be able to take the time to help me with this one :)

Cheers and good work on this project!

**Comment by maciejtreder** [comment]
Hello,

Happy to hear that you like this repo. I did not make any try with @ngx-translate. But that sounds like a nice enhancement. I added it to the backlog :)

**Comment by martinambrus** [comment]
@maciejtreder thanks a lot for implementing this so quickly! I will have a look at it later this afternoon and will let you know the result :)

**Comment by martinambrus** [comment]
After some initial testing, I have some results. For me, it works until you change the default language for the TranslationService.

To be precise, if you change this line: https://github.com/maciejtreder/angular-universal-pwa/blob/master/src/app/app.component.ts#L22 to `this.translate.setDefaultLang('pl');`, once again - the live `npm start` version works correctly but after compilation (`npm run build:prod`) and then running the server (`npm run server`), I'm getting the same Error text as before.

Additionally, I also get this before that Error text is displayed:
```
ERROR { [Error]
  __zone_symbol__currentTask:
   ZoneTask {
     _zone:
      Zone {
        _properties: [Object],
        _parent: [Object],
        _name: 'angular',
        _zoneDelegate: [Object] },
     runCount: 0,
     _zoneDelegates: null,
     _state: 'notScheduled',
     type: 'microTask',
     source: 'Promise.then',
     data: undefined,
     scheduleFn: undefined,
     cancelFn: null,
     callback: [Function],
     invoke: [Function] } }
```

Also, I should probably mention that I'm on Windows 10 here.
I hope we can get this right, and thanks again for reacting so swiftly!

**Comment by maciejtreder** [comment]
Did you check it cross-browser?

**Comment by maciejtreder** [comment]
Ok. I reproduced it on my end. :)

**Comment by maciejtreder** [comment]
@martinambrus Check out with the latest code.

**Comment by martinambrus** [comment]
This seems to fix the issue I was having :)
I will try with my project later today or tomorrow and close this issue if it works there. Thanks again for helping me out with this one!

**Comment by maciejtreder** [comment]
@martinambrus Sound great. Thank you for the donation? Would you like to be mentioned in the app, as a donor?

**Comment by martinambrus** [comment]
@maciejtreder sure, it would be nice to appear there by the name :) thanks! also, is there a way to contact you directly that you'd use frequently, please? I can see FB and Skype contacts on your page but can't find you on Skype and your FB hasn't been updated in some time now :P

cheers!

**Comment by maciejtreder** [comment]
I don't use FB frequently and it's not listed on my home page ;)

That's strange that you couldn't find me on skype. My login is: maciejtreder. You can always reach me via e-mail: contact@maciejtreder.com

**Comment by martinambrus** [comment]
Haha, you're right, it was not FB but Twitter I saw there. But yeah, I did find your FB profile as well through your name and probably have the memory of it being outdated from that point :)

Thanks, I'll try Skype again. And thank you for the translation implementation again!
