### ISSUE TITLE
Cannot run from subfolder

### ISSUE THREAD

**Issue by martinambrus** [maciejtreder/angular-universal-pwa#134]
The way this project now works locally is great but as soon as I deploy it as AWS Lambda, it goes into a subfolder called "production" - which is automatic and cannot be overridden from what I can see. This breaks the project because it tries to load all assets from the root folder.

**Comment by maciejtreder** [comment]
The reason is that URL provided by amazon after deploying, should be used for CNAME of your destination domain (provisioned in AWS API Gateway as a "Custom Domain"). I added code to handle this case on server side, and change base path accordingly.

**Comment by martinambrus** [comment]
Ah, it still doesn't quite load all the stuff from /production on AWS Lambda. I've not tried to do the subdomain thing yet - will try that now, but what's happening with the current code is that for translations, it tries to load JSON files from root folder again, not finding them. I can also see thath the background.png file is also being loaded from the root folder but I guess that's a CSS thing.

I'm sorry for being an ass for trying to run this from a subfolder but it's the fastest way for us to test without actually deploying to the public-facing cloudfront URL, which is much easier to find than the AWS Lambda one.

**Comment by maciejtreder** [comment]
Clear your cache bro and unregister service worker 👍 

<img width="1130" alt="screen shot 2018-03-22 at 5 21 40 pm" src="https://user-images.githubusercontent.com/15926528/37783357-97e59bc0-2df5-11e8-81c1-e79fff3a6a47.png">
