### ISSUE TITLE
Can't resolve moduleName.ngfactory.js

### ISSUE THREAD

**Issue by atodhruv** [maciejtreder/angular-universal-pwa#158]
![error_img](https://user-images.githubusercontent.com/37951869/38161335-df9186c2-34ea-11e8-84fd-4b7278b98dbe.png)

When setup my angular4 theme and try to deploy on aws serverless gives these errors. But localy it works fine. Please help me.

**Comment by maciejtreder** [comment]
Do you have any repository which I could clone to reproduce this problem on my environment?

**Comment by atodhruv** [comment]
I think its a jquery issue.  When I make changes in tsconfig.server.json @ include option. after that when build it gives "**jQuery requires a window with a document**"

**Comment by maciejtreder** [comment]
Probably this article will help:
https://medium.com/@swarnakishore/how-to-include-and-use-jquery-in-angular-cli-project-592e0fe63176

**Comment by maciejtreder** [comment]
@atodhruv Do you still face this issue?

**Comment by atodhruv** [comment]
Yes

**Comment by maciejtreder** [comment]
@atodhruv What about repository? Do you have any which I could clone and reproduce this issue on my end?
