### ISSUE TITLE
Test don't run due to --single-run option

### ISSUE THREAD

**Issue by wstidolph** [maciejtreder/angular-universal-pwa#237]
## I'm submitting a...

<pre><code>
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

Attempt to run tests but get:
<pre>
PS C:\Users\wayne\Projects\VidLessons> npm test

> vid-lessons@0.0.0 test C:\Users\wayne\Projects\VidLessons
> ng test --single-run --code-coverage

Unknown option: '--singleRun'

</pre>

## Expected behavior

Tests would run, once

## Minimal reproduction of the problem with instructions

1. Generate default app (named 'VidLessons' in my case)
2. cd into dir
3. <code>npm test</code> 

Note: <code>ng test</code> runs; the problem is just the single-run  flag that's a problem, it's not among the options listed with <code>ng test --help</code>

## What is the motivation / use case for changing the behavior?

Should be able to test under Angular 6

## Environment
<pre>
PS C:\Users\wayne\Projects\VidLessons> npm list -g --depth=0
C:\Users\wayne\AppData\Roaming\npm
+-- @angular/cli@6.0.0
+-- @ionic/app-scripts@3.1.9
+-- @ngx-rocket/cli@1.6.1
+-- angular-cli@1.0.0-beta.22-1
+-- angular-universal-pwa@2.0.91
+-- bower@1.8.4
+-- cordova@8.0.0
+-- firebase@4.13.1
+-- firebase-tools@3.18.4
+-- generator-jhipster@5.0.0-beta.1
+-- generator-jhipster-ionic@3.2.0
+-- generator-ngx-rocket@4.2.0
+-- graphcool@0.11.6
+-- ionic@3.20.0
+-- npm@6.0.0
+-- typings@2.1.1
+-- webpack@4.6.0
+-- windows-build-tools@2.3.0
+-- yarn@1.6.0
`-- yo@2.0.2

PS C:\Users\wayne\Projects\VidLessons> ng --version
...
Angular CLI: 6.0.0
Node: 9.6.1
OS: win32 x64
Angular: 6.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, http, language-service, material, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.0
@angular-devkit/build-angular     0.6.0
@angular-devkit/build-optimizer   0.6.0
@angular-devkit/core              0.6.0
@angular-devkit/schematics        0.6.0
@ngtools/webpack                  6.0.0
@schematics/angular               0.6.0
@schematics/update                0.6.0
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.6.0

</pre>

Angular version: 6.0.0

Browser:
- [x] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [x] Chrome (iOS) version XX
- [x] Firefox version XX
- [x] Safari (desktop) version XX
- [x] Safari (iOS) version XX
- [x] IE version XX
- [x] Edge version XX
 
For Tooling issues:
- Node version: 9.6.1  
- Platform:  Windows 10 

Others:

</code></pre>

**Comment by maciejtreder** [comment]
@wstidolph Please verify with the latest build.
