### ISSUE TITLE
slow reload

### ISSUE THREAD

**Issue by kodeine** [maciejtreder/angular-universal-pwa#57]
So as per your suggestion i moved to this starter because i could not make the serverless work on the [previous starter](https://github.com/nhutcorp/angular-webpack2-starter). Reloading is very slow in this starter, i changed 1 line of css and it did whole build which was very time consuming.

**Comment by maciejtreder** [comment]
Which script did you use to run the project?

**Comment by kodeine** [comment]
@maciejtreder i used `npm run watch`

**Comment by maciejtreder** [comment]
Ok.
I will take a look at it. 

How long it took to reload project? ~1 minute or more? Is starter from link provided by reloading faster?

**Comment by kodeine** [comment]
i think it took a minute or so, but the starter i mentioned is real quick.
also the other starter uses dev/prod environments. 

i tried to make serverless work on it, i couldnt, would you mind helping the serverless on that starter?

**Comment by maciejtreder** [comment]
I will take a look at this one (angular-universal-pwa) to improve reload time. Thanks for report.

**Comment by maciejtreder** [comment]
@kodeine  Improve merged in #59
